function plot_plot(i, data)
    subplot(3,1,1)
    plot(data(i).distance, data(i).force)
    xlabel('Distance')
    ylabel('Force')
    subplot(3,1,2)
    plot(data(i).time, data(i).distance)
    xlabel('Time')
    ylabel('Distance')
    subplot(3,1,3)
    plot(data(i).time, data(i).force)
    xlabel('Time')
    ylabel('Force')
end